异常：

try
catch
throw

try
{
	throw ...;
}
catch(...)
{

}

1、try/catch不分家，catch可以用...接收任意类型的异常。
2、throw出的错误，可以在catch中捕获，进行对应的处理，一般来说，throw出的变量的类型和catch到的类型必须完全匹配，只有一种特例：子类的对象可以被父类的对象捕获。
3、在某个栈中抛出的错误可以由它的上一层栈（调用者）进行处理。




